Repository ZumDeWald/intl-dates, pull requests merged in 2020-11, with the labels that each got.

#18 Vanilla readme fix
  README.md
Labels: documentation, good first issue, hacktoberfest-accepted

#19 Feature/vanilla final
  hook/index.js
  package.json
  vanilla/index.js
Labels: documentation, enhancement

#20 Bumped version for new release
  package.json
Labels: documentation

#21 Feature/vanilla
  README.md
  hook/index.js
  index.js
  package.json
  vanilla/index.js
Labels: enhancement

#22 VanillaJS version of package ready to push
  README.md
  hook/index.js
  index.js
  package.json
  vanilla/index.js
Labels: documentation, enhancement

#27 Change name to `intl-dates`
  README.md
  package.json
Labels: documentation

#28 Ready for production
  README.md
  package.json
Labels: documentation

#29 Documentation/option date
  README.md
  package.json
Labels: documentation

#30 Feature/option date
  README.md
  hook/index.js
  package.json
  vanilla/index.js
Labels: enhancement

#31 New Feature : Specify Date
  README.md
  hook/index.js
  package.json
  vanilla/index.js
Labels: documentation, enhancement

#32 Fix package name from change to `intl-dates`
  package.json
Labels: documentation

#33 Bug/#25 calculate week
  README.md
  hook/index.js
  package.json
  vanilla/index.js
Labels: bug, documentation

#34 Bug Fix with week start/end dates
  README.md
  hook/index.js
  package.json
  vanilla/index.js
Labels: bug, documentation
